### ISSUE TITLE
Check masking logic

### ISSUE THREAD

**Issue by insoochung** [insoochung/rtl-semantics-design-verification#32]
Verify mask generation logic in BranchVocab class in data/utils.py. Note that the mask is to gather only branch-relevant nodes in a graph. Also, graphs are saved as [batch mode](https://graphneural.network/data-modes/).

**Comment by aarongchan** [comment]
Mask generation logic looks good to me.

**Comment by insoochung** [comment]
Hey @AaronGChan, could you elaborate what checks you've performed before we close this issue?

**Comment by aarongchan** [comment]
Yep, I checked the get_mask function and made sure all operations were correctly implemented and that the resulting mask had the correct graph indexes set to 1.

**Comment by insoochung** [comment]
Thanks @AaronGChan
