### ISSUE TITLE
Various CDFG parsing error for IWLS benchmark designs

### ISSUE THREAD

**Issue by priankasg** [insoochung/rtl-semantics-design-verification#34]
Parsing errors are encountered when attempting to parse the Verible AST from the designs present in the IWLS 2005 benchmark. The problem can be replicated in the following location:

```
cd /mnt/research/Hu_Jiang/Shared/toInsoo
./parse_to_cdfg.sh
```
Out of the 67 designs, only 19 are able to parse the verible json file to a design_graph.pkl

Various parsing errors are encountered for the rest. Some examples are:
```
ac97_ctrl
ac97_ctrl_16fifo
jpegencode
pid_controller
.
.
.
etc
```

**Comment by insoochung** [comment]
Hello, could you provide the commit id of the code you are using?

**Comment by priankasg** [comment]
I am using: b87411201f36c755f340ce83ae5aff2f17a347e9

**Comment by insoochung** [comment]
> I am using: [b874112](https://github.com/insoochung/rtl-semantics-design-verification/commit/b87411201f36c755f340ce83ae5aff2f17a347e9)

Thanks, I will get around to it some time this week.

**Comment by insoochung** [comment]
@priankasg I don't have access to the directory. Could you find a way to share the files with me some other way?

**Comment by priankasg** [comment]
@insoochung please download the files from this link by using your tamu connected google account

https://drive.google.com/file/d/1mO16RDtoy4erswwsNU8S-eDXiRauRS9y/view?usp=sharing

**Comment by insoochung** [comment]
@priankasg The zip file includes modified code from 82f1b6f623949c91508bd0d83e4f86771a65e084. Which one did you use?

**Comment by insoochung** [comment]
I will just work from the current main and on.
